return PlaceObj('ModDef', {
	'title', "Agencies",
	'id', "Agencies",
	'author', "Soundwave2142",
	'version_major', 1,
	'version', 266,
	'lua_revision', 233360,
	'saved_with_revision', 366685,
	'code', {
		"Code/Definitions.lua",
		"Code/Common.lua",
		"Code/Appearance.lua",
		"Code/UI.lua",
		"Code/Debugger.lua",
		"UnitData/DummyTESTAGENCIES.lua",
		"UnitData/DummyTESTAGENCIES2.lua",
	},
	'default_options', {
		AgencyChoice = "Default",
		AgencyRegenerateAttire = "Every 2 weeks",
	},
	'has_data', true,
	'saved', 1753719855,
	'code_hash', 1431862978070541743,
	'affected_resources', {
		PlaceObj('ModResourcePreset', {
			'Class', "Agency",
			'Id', "Merc",
			'ClassDisplayName', "Agency",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Agency",
			'Id', "Adonis",
			'ClassDisplayName', "Agency",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Agency",
			'Id', "Militia",
			'ClassDisplayName', "Agency",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Agency",
			'Id', "Rebels",
			'ClassDisplayName', "Agency",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Agency",
			'Id', "Army",
			'ClassDisplayName', "Agency",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "Agency",
			'Id', "ArmySF",
			'ClassDisplayName', "Agency",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "GeneralAllRounder",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "GeneralDoctor",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "GeneralExplosives",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "GeneralLeader",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "GeneralMarksmen",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "GeneralMechanic",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "Merc",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "AdonisAllRounder",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "AdonisDoctor",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "AdonisExplosives",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "AdonisLeader",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "AdonisMarksmen",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "AdonisMechanic",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "MilitiaAllRounder",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "MilitiaDoctor",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "MilitiaExplosive",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "MilitiaLeader",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "MilitiaMarksmen",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "MilitiaMechanic",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "RebelsAllRounder",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "RebelsDoctor",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "RebelsExplosive",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "RebelsLeader",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "RebelsMarksmen",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "RebelsMechanic",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "Army",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "ArmyAllRounder",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "ArmyDoctor",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "ArmyExplosives",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "ArmyLeader",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "ArmyMarksmen",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AgencyAttirePool",
			'Id', "ArmyMechanic",
			'ClassDisplayName', "Agency Attire Pool",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "MsgDef",
			'Id', "AgenciesApplyAgency",
			'ClassDisplayName', "Message definition",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "PDABrowserLandingMerc",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "PDAAIMBrowserMerc",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "PDAStartButtonMerc",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "PDASatelliteMercAIMMerc",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "PDAAIMBrowserMilitia",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "PDABrowserLandingMilitia",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "PDABrowserLandingRebels",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "PDAAIMBrowserRebels",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "XTemplate",
			'Id', "PDAStartButtonRebels",
			'ClassDisplayName', "UI Template (XTemplate)",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "DummyTESTAGENCIES",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "UnitDataCompositeDef",
			'Id', "DummyTESTAGENCIES2",
			'ClassDisplayName', "Unit",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "NewAppearancePreset",
			'ClassDisplayName', "Appearance preset",
		}),
		PlaceObj('ModResourcePreset', {
			'Class', "AppearancePreset",
			'Id', "NewAppearancePreset2",
			'ClassDisplayName', "Appearance preset",
		}),
	},
	'TagGameSettings', true,
	'TagMercs', true,
	'TagOther', true,
	'TagQuest&Campaigns', true,
	'TagUI', true,
	'TagVisuals&Graphics', true,
})